// debugConsole.js

//generated by o3-mini-high
function setupDebugConsole() {
    // Create a container div for log messages
    const debugDiv = createDiv("");
    debugDiv.id("debugConsole");
    debugDiv.style("position", "fixed");
    debugDiv.style("bottom", "0");
    debugDiv.style("left", "0");
    debugDiv.style("width", "100%");
    debugDiv.style("max-height", "200px");
    debugDiv.style("overflow-y", "auto");
    debugDiv.style("background", "rgba(0,0,0,0.8)");
    debugDiv.style("color", "white");
    debugDiv.style("font-size", "12px");
    debugDiv.style("padding", "5px");
    debugDiv.style("z-index", "9999");
  
    // Save original console functions
    const originalLog = console.log;
    const originalError = console.error;
  
    // Override console.log
    console.log = function(...args) {
      originalLog.apply(console, args);
      const message = args.join(" ");
      debugDiv.html(debugDiv.html() + "<div>LOG: " + message + "</div>");
    };
  
    // Override console.error
    console.error = function(...args) {
      originalError.apply(console, args);
      const message = args.join(" ");
      debugDiv.html(debugDiv.html() + "<div style='color: red;'>ERROR: " + message + "</div>");
    };
  
    // Global error handler
    window.onerror = function(message, source, lineno, colno, error) {
      console.error("Global Error: " + message + " at " + source + ":" + lineno + ":" + colno);
      return true; // Prevent default browser error handler
    };
  }
  